/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as BuscandoRouteImport } from './routes/buscando'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatsIdRouteImport } from './routes/treats.$id'
import { Route as ReservasIdRouteImport } from './routes/reservas.$id'
import { Route as PaseoIdRouteImport } from './routes/paseo.$id'
import { Route as PaseadorIdRouteImport } from './routes/paseador.$id'
import { Route as ConfirmarIdRouteImport } from './routes/confirmar.$id'
import { Route as CompletadoIdRouteImport } from './routes/completado.$id'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscandoRoute = BuscandoRouteImport.update({
  id: '/buscando',
  path: '/buscando',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatsIdRoute = TreatsIdRouteImport.update({
  id: '/treats/$id',
  path: '/treats/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasIdRoute = ReservasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReservasRoute,
} as any)
const PaseoIdRoute = PaseoIdRouteImport.update({
  id: '/paseo/$id',
  path: '/paseo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaseadorIdRoute = PaseadorIdRouteImport.update({
  id: '/paseador/$id',
  path: '/paseador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarIdRoute = ConfirmarIdRouteImport.update({
  id: '/confirmar/$id',
  path: '/confirmar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletadoIdRoute = CompletadoIdRouteImport.update({
  id: '/completado/$id',
  path: '/completado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscando': typeof BuscandoRoute
  '/mensajes': typeof MensajesRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/resultados': typeof ResultadosRoute
  '/chat/$id': typeof ChatIdRoute
  '/completado/$id': typeof CompletadoIdRoute
  '/confirmar/$id': typeof ConfirmarIdRoute
  '/paseador/$id': typeof PaseadorIdRoute
  '/paseo/$id': typeof PaseoIdRoute
  '/reservas/$id': typeof ReservasIdRoute
  '/treats/$id': typeof TreatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscando': typeof BuscandoRoute
  '/mensajes': typeof MensajesRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/resultados': typeof ResultadosRoute
  '/chat/$id': typeof ChatIdRoute
  '/completado/$id': typeof CompletadoIdRoute
  '/confirmar/$id': typeof ConfirmarIdRoute
  '/paseador/$id': typeof PaseadorIdRoute
  '/paseo/$id': typeof PaseoIdRoute
  '/reservas/$id': typeof ReservasIdRoute
  '/treats/$id': typeof TreatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscando': typeof BuscandoRoute
  '/mensajes': typeof MensajesRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/resultados': typeof ResultadosRoute
  '/chat/$id': typeof ChatIdRoute
  '/completado/$id': typeof CompletadoIdRoute
  '/confirmar/$id': typeof ConfirmarIdRoute
  '/paseador/$id': typeof PaseadorIdRoute
  '/paseo/$id': typeof PaseoIdRoute
  '/reservas/$id': typeof ReservasIdRoute
  '/treats/$id': typeof TreatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscando'
    | '/mensajes'
    | '/reservas'
    | '/resultados'
    | '/chat/$id'
    | '/completado/$id'
    | '/confirmar/$id'
    | '/paseador/$id'
    | '/paseo/$id'
    | '/reservas/$id'
    | '/treats/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscando'
    | '/mensajes'
    | '/reservas'
    | '/resultados'
    | '/chat/$id'
    | '/completado/$id'
    | '/confirmar/$id'
    | '/paseador/$id'
    | '/paseo/$id'
    | '/reservas/$id'
    | '/treats/$id'
  id:
    | '__root__'
    | '/'
    | '/buscando'
    | '/mensajes'
    | '/reservas'
    | '/resultados'
    | '/chat/$id'
    | '/completado/$id'
    | '/confirmar/$id'
    | '/paseador/$id'
    | '/paseo/$id'
    | '/reservas/$id'
    | '/treats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscandoRoute: typeof BuscandoRoute
  MensajesRoute: typeof MensajesRoute
  ReservasRoute: typeof ReservasRouteWithChildren
  ResultadosRoute: typeof ResultadosRoute
  ChatIdRoute: typeof ChatIdRoute
  CompletadoIdRoute: typeof CompletadoIdRoute
  ConfirmarIdRoute: typeof ConfirmarIdRoute
  PaseadorIdRoute: typeof PaseadorIdRoute
  PaseoIdRoute: typeof PaseoIdRoute
  TreatsIdRoute: typeof TreatsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscando': {
      id: '/buscando'
      path: '/buscando'
      fullPath: '/buscando'
      preLoaderRoute: typeof BuscandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treats/$id': {
      id: '/treats/$id'
      path: '/treats/$id'
      fullPath: '/treats/$id'
      preLoaderRoute: typeof TreatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas/$id': {
      id: '/reservas/$id'
      path: '/$id'
      fullPath: '/reservas/$id'
      preLoaderRoute: typeof ReservasIdRouteImport
      parentRoute: typeof ReservasRoute
    }
    '/paseo/$id': {
      id: '/paseo/$id'
      path: '/paseo/$id'
      fullPath: '/paseo/$id'
      preLoaderRoute: typeof PaseoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paseador/$id': {
      id: '/paseador/$id'
      path: '/paseador/$id'
      fullPath: '/paseador/$id'
      preLoaderRoute: typeof PaseadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar/$id': {
      id: '/confirmar/$id'
      path: '/confirmar/$id'
      fullPath: '/confirmar/$id'
      preLoaderRoute: typeof ConfirmarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completado/$id': {
      id: '/completado/$id'
      path: '/completado/$id'
      fullPath: '/completado/$id'
      preLoaderRoute: typeof CompletadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservasRouteChildren {
  ReservasIdRoute: typeof ReservasIdRoute
}

const ReservasRouteChildren: ReservasRouteChildren = {
  ReservasIdRoute: ReservasIdRoute,
}

const ReservasRouteWithChildren = ReservasRoute._addFileChildren(
  ReservasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscandoRoute: BuscandoRoute,
  MensajesRoute: MensajesRoute,
  ReservasRoute: ReservasRouteWithChildren,
  ResultadosRoute: ResultadosRoute,
  ChatIdRoute: ChatIdRoute,
  CompletadoIdRoute: CompletadoIdRoute,
  ConfirmarIdRoute: ConfirmarIdRoute,
  PaseadorIdRoute: PaseadorIdRoute,
  PaseoIdRoute: PaseoIdRoute,
  TreatsIdRoute: TreatsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
